apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP_NAME
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: xtreme1
      app.kubernetes.io/instance: xtreme1
      app.kubernetes.io/component: $APP_NAME
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xtreme1
        app.kubernetes.io/instance: xtreme1
        app.kubernetes.io/component: $APP_NAME
    spec:
      nodeSelector:
        dedicated: model
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - xtreme1
                - key: "app.kubernetes.io/instance"
                  operator: In
                  values:
                  - xtreme1
                - key: "app.kubernetes.io/component"
                  operator: In
                  values:
                  - $APP_NAME
              topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: basicai-registry
      containers:
        - name: $APP_NAME
          image: $IMAGE
          args:
            - --num_processes=1
          resources:
            requests:
              memory: 1Gi
              cpu: 100m
            limits:
              aliyun.com/gpu-mem: 4
              aliyun.com/gpu-core.percentage: 50
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  selector:
    app.kubernetes.io/name: xtreme1
    app.kubernetes.io/instance: xtreme1
    app.kubernetes.io/component: $APP_NAME
  ports:
    - name: http
      port: 80
      targetPort: 5000
